title: Dhaval Portfolio
description: Solo Developer & Tech Explorer
baseurl: "https://dhaval-vedra.github.io/Lowmind-api/https://dhaval-vedra.github.io/Lowmind-api/"
url: "https://dhaval-vedra.github.io/Lowmind-api/"
theme: null  # Disable default theme
